services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole-primary

    environment:
      TZ: America/Los_Angeles
      FTLCONF_webserver_api_password: "${PIHOLE_ADMIN_PASSWORD:?Set PIHOLE_ADMIN_PASSWORD}"
      FTLCONF_ntp_ipv4_active: "false"
      FTLCONF_ntp_ipv6_active: "false"
      FTLCONF_ntp_sync_active: "false"

    volumes:
      - ./etc-pihole:/etc/pihole

    networks:
      pihole_lan:
        ipv4_address: 192.0.2.4

    restart: unless-stopped

networks:
  pihole_lan:
    external: true
    name: pihole_lan
